#!/bin/bash
#The cookie needs to be set in the following variable to be able to download the OpenVPN client config
COOKIE=
clear
PS3="Choose from the list of actions for the customVPN setup : "
 
# set options
select options in 'update server' 'users online' 'create new user' 'install nsis & pritunl on fresh ubuntu install'
do
	case $options in
		'update server')
			echo "--------------"
			echo "updating repos, might take a minute"
			echo
			sudo apt-get -q=2 update && sudo apt-get upgrade
			echo
			echo "--------------"		
			;;
                'users online')
                        echo "--------------"           
			echo
                        USERS_ONLINE=$(python pyscripts/pythonscript_get_server_info.py)
			echo
			echo "$USERS_ONLINE user(s) online at the moment"
                        echo "--------------"           
                        ;;
                'create new user')
                        echo "--------------"           
                        echo "Type the name of the new user you want to create, followed by [ENTER]:"
			read NEWUSER
			#changes spaces to underscore and converts non-roman to ASCII
			NORM_NEWUSER=$(echo "$NEWUSER" | tr ' ' '_' | iconv --to-code ASCII//TRANSLIT)
			#edit pythonscript to create new user with the given name ($NORM_NEWUSER)
			sed "s/~~~~~/$NORM_NEWUSER/g" pyscripts/pythonscript_new_user.py > pyscripts/pythonscript_new_user_"$NORM_NEWUSER".py
			#fetch the org ID which is required for the API call for creating a new user
			ORG_ID=$(python pyscripts/pythonscript_org_id.py)
			#edit pythonscript to include org ID
			sed -i "s/@@@@@/$ORG_ID/g" pyscripts/pythonscript_new_user_"$NORM_NEWUSER".py
			NEW_USER_ID=$(python pyscripts/pythonscript_new_user_"$NORM_NEWUSER".py)
			echo "New user named: '$NORM_NEWUSER' has been created"
			echo
			echo "Do you want to generate a custom OpenVPN windows client exe? [Y/n]"
			read RESPONSE
			if [ "$RESPONSE" != 'n|N|No|no|nO|nein|Nein|Ne|ne|non|Non' ]
			then
				echo "OK, embedding opvn config into executable"
				echo
				echo "**************************************************"
				##get_config API call not working, getting InternalServerError 500	
				##edit pythonscript to input the correct ORG ID and NORM_NEWUSER			
				#sed "s/~~~~~/$ORG_ID/g" pyscripts/pythonscript_get_config.py > pyscripts/pythonscript_get_config_"$NORM_NEWUSER".py
				#sed -i "s/@@@@@/$NEW_USER_ID/g" pyscripts/pythonscript_get_config_"$NORM_NEWUSER".py
				##suppose to pull a tar file with the ovpn client config
				#pyscripts/pythonscript_get_config_"$NORM_NEWUSER".py
				#tar xvf *.tar
				#since API for downloading OpenVPN config for user isn't functioning, this is a 'backup' option using curl
				#IMPORTANT - the cookie needs to be saved and pasted into the file 'cauth'. 
				#This cookie can be generated by installing the 'cliget' firefox add on and downloading a user's config and then capturing the cookie within the extension
				curl -k --header "Cookie: session=$COOKIE" "https://192.81.211.210:9700/key/$ORG_ID/$NEW_USER_ID.tar" -o "$NORM_NEWUSER".tar &&
				echo
				echo "Downloaded and untarred following file:"
				tar xvf *.tar
				echo "**************************************************"
				#changing OpenVPN client config text according to the contents of 'VPNtext'
				/bin/bash client_config_editor.sh
				echo "**************************************************"
				sed "s/@@@@@/$NORM_NEWUSER/g" openvpn_installer_script.nsi > openvpn_installer_script_"$NORM_NEWUSER".nsi
				sed -i "s/~~~~~/$NORM_NEWUSER/g" openvpn_installer_script_"$NORM_NEWUSER".nsi
				#starting script to create windows executable
				makensis openvpn_installer_script_"$NORM_NEWUSER".nsi
				echo "**************************************************"
				#removing customized scripts
	                        rm -f pyscripts/pythonscript_new_user_"$NORM_NEWUSER".py pyscripts/pythonscript_get_config_"$NORM_NEWUSER".py pyscripts/pythonscript_new_user_"$NORM_NEWUSER".py openvpn_installer_script_"$NORM_NEWUSER".nsi *.tar *.ovpne
				#move configs and installers to folder
				mv *.ovpn *.exe ./archived_installers_configs/
				clear
				echo "custom OpenVPN installer named 'vpn-installer_"$NORM_NEWUSER".exe' successfully created:"
				find . -name "*"$NORM_NEWUSER".exe" 				
			fi
			echo "--------------"           
                        ;;
		'install nsis on fresh install')		
			echo "--------------"   
			/bin/bash ./nsis_install.sh
			echo "--------------"   
			;;	
		*)		
			echo "Error: Please try again (select 1..9)!"
			;;		
	esac
done
